services:
  smart-playlist:
    image: ghcr.io/venkatpandey/go-navi-smart-playlist:latest
    container_name: smart-playlist
    restart: unless-stopped
    environment:
      NAVIDROME_URL: http://navidrome:4533
      NAVIDROME_USER: your-user
      NAVIDROME_PASSWORD: your-password
      PLAYLIST_SIZE: "50"
      DRY_RUN: "false"
      ENABLE_STATE_CACHE: "true"
      STATE_FILE: /data/smart-playlist/your-user/state.json
    volumes:
      - /volume1/docker/navidrome/data:/data
